Fix macos workflow
+ Use brew versions for checking the system libraries
between build and test steps. This avoid the circumstances
that the brew system libraries change during build.

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -1,23 +1,27 @@
 name: macOS built test
-
 on:
   schedule:
     - cron: 3 4 * * 0
       timezone: "Europe/Berlin"
   workflow_dispatch:
-
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
-
 jobs:
   build:
     name: Build 4C on macOS
     runs-on: macos-26
+    outputs:
+      brew-version-hash: ${{ steps.brew-versions.outputs.hash }}
     steps:
       - uses: actions/checkout@v7
       - name: System preparation
         run: ./dependencies/darwin/prepare_system.sh
+      - name: Get Homebrew versions
+        id: brew-versions
+        run: |
+          # Generate a key of all brew libraries
+          echo "hash=$(brew list --versions | sha256sum | awk '{print $1}')" >> $GITHUB_OUTPUT
       - name: Restore dependencies cache
         id: cache-deps
         uses: actions/cache/restore@v6
@@ -37,13 +41,13 @@ jobs:
         with:
           path: ${{ env.HOME }}/opt
           key: ${{ runner.os }}-deps-${{ hashFiles('./dependencies/darwin/compile_dependencies.sh', 'dependencies/darwin/**/install.sh',
-            'dependencies/current/**/install.sh') }}
+            'dependencies/current/**/install.sh') }}-brew-${{ steps.brew-versions.outputs.hash }}
       - name: Restore build cache
         id: cache-build
         uses: actions/cache/restore@v6
         with:
           path: build/
-          key: ${{ runner.os }}-build-${{ github.sha }}
+          key: ${{ runner.os }}-build-${{ github.sha }}-brew-${{ steps.brew-versions.outputs.hash }}
       - name: Build 4C
         if: steps.cache-build.outputs.cache-hit != 'true'
         run: |
@@ -56,8 +60,7 @@ jobs:
         uses: actions/cache/save@v6
         with:
           path: build/
-          key: ${{ runner.os }}-build-${{ github.sha }}
-
+          key: ${{ runner.os }}-build-${{ github.sha }}-brew-${{ steps.brew-versions.outputs.hash }}
   test:
     name: Test 4C on macOS
     needs: build
@@ -66,19 +69,36 @@ jobs:
       - uses: actions/checkout@v7
       - name: System preparation
         run: ./dependencies/darwin/prepare_system.sh
+      - name: Get Homebrew versions
+        id: brew-versions
+        run: |
+          # Generate a key of all brew libraries
+          echo "hash=$(brew list --versions | sha256sum | awk '{print $1}')" >> $GITHUB_OUTPUT
+      - name: Check if the hash differs from the hash in the build job
+        if: steps.brew-versions.outputs.hash != needs.build.outputs.brew-version-hash
+        run: |
+          {
+            echo "### Changed system libraries!"
+            echo ""
+            echo "The test job aborted because the brew system libraries changed after the build job completed."
+            echo "The system libraries installed in the test job have a different version than the ones used in the build job to build the dependencies and 4C."
+            echo ""
+            echo "This should rarely happen. A re-run of the workflow should solve this problem."
+          } >> $GITHUB_STEP_SUMMARY
+          exit 1
       - name: Restore dependencies cache
         id: cache-deps
         uses: actions/cache/restore@v6
         with:
           path: ${{ env.HOME }}/opt
           key: ${{ runner.os }}-deps-${{ hashFiles('./dependencies/darwin/compile_dependencies.sh', 'dependencies/darwin/**/install.sh',
-            'dependencies/current/**/install.sh') }}
+            'dependencies/current/**/install.sh') }}-brew-${{ steps.brew-versions.outputs.hash }}
       - name: Restore build cache
         id: cache-build
         uses: actions/cache/restore@v6
         with:
           path: build/
-          key: ${{ runner.os }}-build-${{ github.sha }}
+          key: ${{ runner.os }}-build-${{ github.sha }}-brew-${{ steps.brew-versions.outputs.hash }}
       - name: Run tests
         run: |
           echo "tests"
